ORDERS = {
    "ORD-1001": {
        "customer_name": "Rahul Sharma",
        "item": "Sony WH-1000XM5 Headphones",
        "status": "out_for_delivery",
        "expected_delivery": "Today by 8 PM",
        "cancellable": False,
        "refund_status": None,
        "amount": 24990,
    },
    "ORD-1002": {
        "customer_name": "Priya Patel",
        "item": "boAt Airdopes 141",
        "status": "processing",
        "expected_delivery": "Aug 10, 2026",
        "cancellable": True,
        "refund_status": None,
        "amount": 1299,
    },
    "ORD-1003": {
        "customer_name": "Amit Verma",
        "item": "Logitech MX Master 3 Mouse",
        "status": "delivered",
        "expected_delivery": "Delivered on Aug 2, 2026",
        "cancellable": False,
        "refund_status": "processed",
        "amount": 8495,
    },
    "ORD-1004": {
        "customer_name": "Sneha Nair",
        "item": "Redmi Note 13 Pro",
        "status": "shipped",
        "expected_delivery": "Aug 8, 2026",
        "cancellable": False,
        "refund_status": None,
        "amount": 21999,
    },
    "ORD-1005": {
        "customer_name": "Karan Mehta",
        "item": "Anker 65W GaN Charger",
        "status": "processing",
        "expected_delivery": "Aug 9, 2026",
        "cancellable": True,
        "refund_status": None,
        "amount": 2499,
    },
}
